# Generated by Django 5.2.8 on 2025-11-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
