[project]
name = "learning-platform-pt"
version = "0.1.0"
description = ""
authors = [
    {name = "Tatiana Pitieva",email = "tatyane.liss@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=5.2.8,<6.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "pillow (>=12.0.0,<13.0.0)",
    "black (>=25.11.0,<26.0.0)",
    "django-filter (>=25.2,<26.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "ipython (>=9.7.0,<10.0.0)",
    "coverage (>=7.12.0,<8.0.0)",
    "drf-yasg (>=1.21.11,<2.0.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)",
    "stripe (>=14.0.1,<15.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
