# Generated by Django 5.2.8 on 2025-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_stripe_price_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последней отправки уведомления подписчикам",
                null=True,
                verbose_name="Время последнего уведомления",
            ),
        ),
    ]
