name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/github_actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        env:
          CI: true
        run: |
          poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/learning_platform_pt
            git pull origin feature/github_actions
            poetry install
            sudo systemctl restart gunicorn
